- name: Set global private ip variable
  lineinfile:
    dest: /etc/environment
    line: "PRIVATE_IPV4={{ansible_ssh_host}}"

- name: Set cluster discovery url
  lineinfile:
    dest: /etc/environment
    line: "DISCOVERY_URL={{discovery_url}}"

- name: Set fleet ip
  lineinfile:
    dest: /etc/environment
    line: "FLEET_PUBLIC_IP={{ansible_ssh_host}}"

- name: Increase hard ulimit for influxdb
  lineinfile:
    dest: /etc/security/limits.conf
    line: "*             hard    nofile          65536"

- name: Increase soft ulimit for influxdb
  lineinfile:
    dest: /etc/security/limits.conf
    line: "*             soft    nofile          65536"
