- name: install cloudera manager dependencies
  apt: name={{ item }} state=present
  with_items:
    - cloudera-manager-server
    - cloudera-manager-server-db-2

- name: start cloudera services
  service: name={{item}} state=started enabled=yes
  with_items:
    - cloudera-scm-server-db
    - cloudera-scm-server
