- name: Download fleet archive
  get_url:
    url: https://github.com/coreos/fleet/releases/download/v0.8.3/fleet-v0.8.3-linux-amd64.tar.gz
    dest: /tmp/fleet-v0.8.3-linux-amd64.tar.gz

- name: Unarchive and install fleetd
  unarchive:
    src: /tmp/fleet-v0.8.3-linux-amd64.tar.gz
    dest: /opt/
    copy: no

- name: Symlink fleetd to /usr/local/bin
  file:
    src: /opt/fleet-v0.8.3-linux-amd64/fleetd
    dest: /usr/local/bin/fleetd
    state: link

- name: Symlink fleetctl to /usr/local/bin
  file:
    src: /opt/fleet-v0.8.3-linux-amd64/fleetctl
    dest: /usr/local/bin/fleetctl
    state: link

- name: Install etcd service file
  copy: src=fleetd.service dest=/usr/lib/systemd/system/fleetd.service

- name: Start and register fleetd service file
  service: name=fleetd enabled=yes state=restarted
