- name: Setup all hosts with etcd
  hosts: all
  gather_facts: false
  sudo: true
  roles:
    - unique
    - environment
    - etcd
    - docker

- name: Influxdb Nodes
  hosts: influxdb
  gather_facts: false
  sudo: true
  roles:
    - influxdb

- name: Haproxy Nodes
  hosts: haproxy
  gather_facts: false
  sudo: true
  roles:
    - confd
    - haproxy
    - influxdb-load-test
    - graphana
