- name: Setup all hosts with docker
  hosts: all
  gather_facts: false
  sudo: true
  roles:
    - unique
    - environment
    - etcd
    - docker
    - influxdb

- name: Haproxy Nodes
  hosts: haproxy
  gather_facts: false
  sudo: true
  roles:
    - confd
    - haproxy
