- name: Create graphana directory for start script
  file: path=/etc/graphana state=directory

- name: Install graphana_start script
  copy: src=start_graphana dest=/etc/graphana/start_graphana mode=0755

- name: Install graphana service file
  copy: src=graphana.service dest=/usr/lib/systemd/system/graphana.service

- name: Start Graphana
  service: name=graphana enabled=yes state=started
