- name: install ambari server
  apt: name=ambari-server state=latest
  register: ambari_installed

- name: setup ambari server and accept all defaults
  shell: ambari-server setup -s
  when: ambari_installed.changed

- name: start ambari server
  service: name=ambari-server state=started enabled=yes
