- name: install ambari agent
  apt: name=ambari-agent state=latest

# - name: install ambari agent confi
#   copy: src=ambari-agent.ini dest=/etc/ambari-agent/conf/ambari-agent.ini
- name: set ambari server to contact
  lineinfile:
    dest: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: 'hostname=.*'
    line: "hostname=hdp-01"
    state: present

- name: start ambari agent
  service: name=ambari-agent state=started enabled=yes
